version: "3.1"

services:
  client:
    container_name: web_client
    build: 
      context: ./client
      dockerfile: Dockerfile
    #restart: always
    ports: 
      - "3000:3000"
    working_dir: /client/src/app
    volumes: 
      - ./client:/client/src/app
    entrypoint: ["npm", "start"]
    links: 
      - server
    networks: 
      - webappnetwork

  server:
    container_name: web_server
    build: 
      context: ./server
      dockerfile: Dockerfile
    #restart: always
    ports: 
      - "9000:9000"
    volumes: 
      - ./server:/server
      - /server/node_modules
    networks: 
      - webappnetwork

  postgres:
    container_name: postgres_container
    image: postgres:11.6
    environment: 
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports: 
      - "5432:5432"
    networks: 
      - postgres

networks: 
  webappnetwork:
    driver: bridge
  postgres:
    driver: bridge